// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiCareSystem.Data.Models;

public partial class WaterParameterLimit
{
    public int ParameterId { get; set; }

    public string ParameterName { get; set; }

    public decimal MinValue { get; set; }

    public decimal MaxValue { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}