// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiCareSystem.Data.Models;

public partial class WaterParameterLimit
{
    public int ParameterId { get; set; }

    public string ParameterName { get; set; }

    public decimal MinGoodValue { get; set; }

    public decimal MaxGoodValue { get; set; }

    public decimal MinAcceptValue { get; set; }

    public decimal MaxAcceptValue { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}