// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiCareSystem.Data.Models;

public partial class User
{
    public long Id { get; set; }

    public string Email { get; set; }

    public string PashwordHash { get; set; }

    public long RoleId { get; set; }

    public string EmailVerifiedToken { get; set; }

    public bool EmailVerified { get; set; }

    public virtual ICollection<Blog> Blogs { get; set; } = new List<Blog>();

    public virtual ICollection<KoiFish> KoiFishes { get; set; } = new List<KoiFish>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<Pond> Ponds { get; set; } = new List<Pond>();

    public virtual Role Role { get; set; }
}