version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: KoiCareSystem.RazorWebApp/Dockerfile  # Đường dẫn đến Dockerfile của ứng dụng
    volumes:
      - ./dataprotection-keys:/root/.aspnet/DataProtection-Keys 
    ports:
      - "8080:80"  # Map port 8080 trên host đến port 80 trong container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Cấu hình môi trường